---
- hosts: amqap
  name: jboss amq setup
  become: "{{ use_sudo|default(True) }}"
  roles:
    - role: java_openjdk
      openjdk_version: "1.7.0"
    - role: java_keystore
      jksdest: /opt/certs/g4.keystore
    - role: amqap
      amq_heap_size: "{{'4' if working_environment[3:6] in ['dev'] else '6'}}"
    - role: filebeat
      filebeat_collectables:
        - source:
            name: "amqap11"
            type: log
            paths: "[\"/var/log/messages\"]"
            exclude_files: "[\".gz$\"]"
            fields:
              env: "{{ working_environment }}"
              app_id: "amqap11"
              category: "amqap11"
              sourcecategory: "amqap11_{{ working_environment }}"
              source: "amqap11"
              fields_under_root: true
        # multiline_pattern: '^[[:digit:]]{2}:[[:digit:]]{2}:[[:digit:]]{2}|^[[:digit:]]{4}-[[:digit:]]{2}-[[:digit:]]{2}'
        # multiline_pattern '^[0-9]{4}\/[0-9]{2}\/[0-9]{2}'
        # multiline_negate: 'true'
        # multiline_match: 'after'
        # processors:
        #   timestamp: true
        #   target_prefix: "{{ stack_name }}"
      when:
       - working_environment[0:3] in ['aws'] and working_environment[3:6] not in ['prd']
      tags:
       - filebeat
